/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  '/logs': {
    /** Retrieve latest server logs */
    get: operations['getLogs'];
  };
  '/default': {
    /** get default route */
    get: operations['getDefault'];
    /** post default route */
    post: operations['postDefault'];
    /** delete default route */
    delete: operations['deleteDefault'];
    /** path default route */
    patch: operations['patchDefault'];
  };
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    ApiErrorModel: {
      error: string;
    };
    SuccessModel: {
      success: boolean;
    };
    MessageModel: {
      message: string;
    };
    /** @description Server log entry */
    Log: {
      /** @description Log message */
      message: string;
      /** @description Log timestamp in seconds */
      time: number;
      /** @enum {string} */
      level: 'debug' | 'info' | 'warn' | 'error';
    };
    DefaultPostModel: {
      name: string;
    };
    DefaultPatchModel: {
      name: string;
    };
  };
  responses: {
    /** @description Successful operation */
    204: {
      content: never;
    };
    /** @description Bad Request */
    400: {
      content: {
        'application/json': components['schemas']['ApiErrorModel'];
      };
    };
    /** @description Unauthorized */
    401: {
      content: {
        'application/json': components['schemas']['ApiErrorModel'];
      };
    };
    /** @description Forbidden */
    403: {
      content: {
        'application/json': components['schemas']['ApiErrorModel'];
      };
    };
    /** @description Resource not found */
    404: {
      content: {
        'application/json': components['schemas']['ApiErrorModel'];
      };
    };
    /** @description Conflict */
    409: {
      content: {
        'application/json': components['schemas']['ApiErrorModel'];
      };
    };
    /** @description Server is busy */
    503: {
      content: {
        'application/json': components['schemas']['ApiErrorModel'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {

  /** Retrieve latest server logs */
  getLogs: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Log'][];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
    };
  };
  /** get default route */
  getDefault: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['MessageModel'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
    };
  };
  /** post default route */
  postDefault: {
    requestBody: {
      content: {
        'application/json': components['schemas']['DefaultPostModel'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['MessageModel'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
    };
  };
  /** delete default route */
  deleteDefault: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['MessageModel'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
    };
  };
  /** path default route */
  patchDefault: {
    requestBody: {
      content: {
        'application/json': components['schemas']['DefaultPatchModel'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['MessageModel'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ApiErrorModel'];
        };
      };
    };
  };
}
